src/futuresboard/blueprint.py
from __future__ import annotations

import csv
import os
from datetime import date
from datetime import datetime
from datetime import timedelta
from typing import Any

import requests
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask.helpers import url_for
from flask import current_app
from typing_extensions import TypedDict

from futuresboard import db

app = Blueprint("main", __name__)


class CoinsTotals(TypedDict):
    active: int
    inactive: int
    buys_long: int
    sells_long: int
    pbr_long: int
    buys_short: int
    sells_short: int
    pbr_short: int


class Coins(TypedDict):
    active: dict[str, tuple[int, int, int]]
    inactive: list[str]
    totals: CoinsTotals
    warning: bool


class History(TypedDict):
    columns: list[dict[str, Any]]


class Projections(TypedDict):
    dates: list[str]
    proj: dict[float, list[float]]
    pcustom: list[float]
    pcustom_value: float


remove_incomeTypes = ["TRANSFER", "COIN_SWAP_DEPOSIT", "COIN_SWAP_WITHDRAW"]


def zero_value(x):
    if x is None:
        return 0
    else:
        return x


def format_dp(value, dp=2):
    return "{:.{}f}".format(value, dp)


def calc_pbr(volume, price, side, balance):
    if price > 0.0:
        if side == "SHORT":
            return abs(volume * price) / balance
        elif side == "LONG":
            return abs(volume * price) / balance
    return 0.0


def average_down_target(posprice, posqty, currentprice, targetprice):
    return (posqty * (posprice - targetprice)) / (targetprice - currentprice)


def get_coins():
    coins: Coins = {
        "active": {},
        "inactive": [],
        "totals": {"active": 0, "inactive": 0, "buys_long": 0, "sells_long": 0, "pbr_long": 0, "buys_short": 0, "sells_short": 0, "pbr_short": 0},
        "warning": False,
    }

    all_active_positions = db.query(
        "SELECT symbol, entryPrice, positionSide, positionAmt FROM positions WHERE ABS(positionAmt) > 0 ORDER BY symbol ASC"
    )

    all_symbols_with_pnl = db.query(
        'SELECT DISTINCT(symbol) FROM income WHERE asset <> "BNB" AND symbol <> "" AND incomeType NOT IN'
        + " ({0})".format(", ".join("?" for _ in remove_incomeTypes))
        + " ORDER BY symbol ASC",
        remove_incomeTypes,
    )

    balance = db.query("SELECT totalWalletBalance FROM account WHERE AID = 1", one=True)

    active_symbols = []
    pbr_long, pbr_short = 0.0, 0.0

    for position in all_active_positions:
        if position[0] not in active_symbols:
            coins["totals"]["active"] += 1
        active_symbols.append(position[0])

        buy_long, sell_long, buy_short, sell_short,  = 0, 0, 0, 0

        buyorders_long = db.query(
            'SELECT COUNT(OID) FROM orders WHERE symbol = ? AND side = "BUY" AND positionSide = "LONG"',
            [position[0]],
            one=True,
        )

        buyorders_short = db.query(
            'SELECT COUNT(OID) FROM orders WHERE symbol = ? AND side = "BUY" AND positionSide = "SHORT"',
            [position[0]],
            one=True,
        )

        sellorders_long = db.query(
            'SELECT COUNT(OID) FROM orders WHERE symbol = ? AND side = "SELL" AND positionSide = "LONG"',
            [position[0]],
            one=True,
        )

        sellorders_short = db.query(
            'SELECT COUNT(OID) FROM orders WHERE symbol = ? AND side = "SELL" AND positionSide = "SHORT"',
            [position[0]],
            one=True,
        )

        coins["active"][position[0]] = [buy_long, sell_long, pbr_long, buy_short, sell_short, pbr_short]
        if position[2] == 'LONG':
            pbr_long = round(calc_pbr(position[3], position[1], position[2], float(balance[0])), 2)
            pbr_short = 0.0
        if position[2] == 'SHORT':
            pbr_short = round(calc_pbr(position[3], position[1], position[2], float(balance[0])), 2)
            pbr_long = 0.0

        if buyorders_long is not None:
            buy_long = int(buyorders_long[0])
        if sellorders_long is not None:
            sell_long = int(sellorders_long[0])
        if buyorders_short is not None:
            buy_short = int(buyorders_short[0])
        if sellorders_short is not None:
            sell_short = int(sellorders_short[0])
        if buy_long == 0 and sell_long == 0 and buy_short == 0 and sell_short == 0:
            coins["warning"] = True

        coins["active"][position[0]][0] = buy_long
        coins["active"][position[0]][1] = sell_long
        coins["active"][position[0]][2] += pbr_long
        coins["active"][position[0]][3] = buy_short
        coins["active"][position[0]][4] = sell_short
        coins["active"][position[0]][5] += pbr_short
        coins["totals"]["buys_long"] += buy_long
        coins["totals"]["sells_long"] += sell_long
        coins["totals"]["pbr_long"] += pbr_long
        coins["totals"]["buys_short"] += buy_short
        coins["totals"]["sells_short"] += sell_short
        coins["totals"]["pbr_short"] += pbr_short
        coins["active"][position[0]][2] = round(coins["active"][position[0]][2],2)
        coins["active"][position[0]][5] = round(coins["active"][position[0]][5],2)

    for symbol in all_symbols_with_pnl:
        if symbol[0] not in active_symbols:
            coins["inactive"].append(symbol[0])
            coins["totals"]["inactive"] += 1
    
    coins["totals"]["pbr_long"] = format_dp(coins["totals"]["pbr_long"])
    coins["totals"]["pbr_short"] = format_dp(coins["totals"]["pbr_short"])
    return coins


def get_lastupdate():
    lastupdate = db.query("SELECT MAX(time) FROM orders", one=True)
    if lastupdate[0] is None:
        return "-"
    return datetime.fromtimestamp(lastupdate[0] / 1000.0).strftime("%Y-%m-%d %H:%M:%S")


def timeranges():
    today = date.today()
    yesterday_start = today - timedelta(days=1)

    this_week_start = today - timedelta(days=today.weekday())
    last_week_start = this_week_start - timedelta(days=7)
    last_week_end = this_week_start - timedelta(days=1)

    this_month_start = today.replace(day=1)
    last_month_start = (this_month_start - timedelta(days=1)).replace(day=1)
    last_month_end = this_month_start - timedelta(days=1)

    this_year_start = today.replace(day=1).replace(month=1)
    last_year_start = (this_year_start - timedelta(days=1)).replace(day=1).replace(month=1)
    last_year_end = this_year_start - timedelta(days=1)

    return [
        [today.strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")],
        [yesterday_start.strftime("%Y-%m-%d"), yesterday_start.strftime("%Y-%m-%d")],
        [this_week_start.strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")],
        [last_week_start.strftime("%Y-%m-%d"), last_week_end.strftime("%Y-%m-%d")],
        [this_month_start.strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")],
        [last_month_start.strftime("%Y-%m-%d"), last_month_end.strftime("%Y-%m-%d")],
        [this_year_start.strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")],
        [last_year_start.strftime("%Y-%m-%d"), last_year_end.strftime("%Y-%m-%d")],
        [last_year_start.strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")],
    ]


@app.route("/", methods=["GET"])
def index_page():
    daterange = request.args.get("daterange")
    ranges = timeranges()

    if daterange is not None:
        daterange = daterange.split(" - ")
        if len(daterange) == 2:
            try:
                start = (
                    datetime.combine(
                        datetime.fromisoformat(daterange[0]), datetime.min.time()
                    ).timestamp()
                    * 1000
                )
                end = (
                    datetime.combine(
                        datetime.fromisoformat(daterange[1]), datetime.max.time()
                    ).timestamp()
                    * 1000
                )
                startdate, enddate = daterange[0], daterange[1]
                return redirect(url_for("main.dashboard_page", start=startdate, end=enddate))
            except Exception:
                pass

    todaystart = (
        datetime.combine(datetime.fromisoformat(ranges[0][0]), datetime.min.time()).timestamp()
        * 1000
    )
    todayend = (
        datetime.combine(datetime.fromisoformat(ranges[0][1]), datetime.max.time()).timestamp()
        * 1000
    )
    weekstart = (
        datetime.combine(datetime.fromisoformat(ranges[2][0]), datetime.min.time()).timestamp()
        * 1000
    )
    weekend = (
        datetime.combine(datetime.fromisoformat(ranges[2][1]), datetime.max.time()).timestamp()
        * 1000
    )
    monthstart = (
        datetime.combine(datetime.fromisoformat(ranges[4][0]), datetime.min.time()).timestamp()
        * 1000
    )
    monthend = (
        datetime.combine(datetime.fromisoformat(ranges[4][1]), datetime.max.time()).timestamp()
        * 1000
    )

    start = (
        datetime.combine(datetime.fromisoformat(ranges[2][0]), datetime.min.time()).timestamp()
        * 1000
    )
    end = (
        datetime.combine(datetime.fromisoformat(ranges[2][1]), datetime.max.time()).timestamp()
        * 1000
    )
    startdate, enddate = ranges[2][0], ranges[2][1]

    balance = db.query("SELECT totalWalletBalance FROM account WHERE AID = 1", one=True)
    total = db.query(
        'SELECT SUM(income) FROM income WHERE asset <> "BNB" AND incomeType NOT IN'
        + " ({0})".format(", ".join("?" for _ in remove_incomeTypes)),
        remove_incomeTypes,
        one=True,
    )
    today = db.query(
        'SELECT SUM(income) FROM income WHERE asset <> "BNB" AND incomeType NOT IN'
        + " ({0})".format(", ".join("?" for _ in remove_incomeTypes))
        + " AND time >= ? AND time <= ?",
        remove_incomeTypes + [todaystart, todayend],
        one=True,
    )
    week = db.query(
        'SELECT SUM(income) FROM income WHERE asset <> "BNB" AND incomeType NOT IN'
        + " ({0})".format(", ".join("?" for _ in remove_incomeTypes))

src/futuresboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block autoreload %}{% endblock %}
        {% if coin_list['warning'] %}
            <link rel="shortcut icon" href="{{ url_for('static', filename='favicon2.ico') }}">
        {% else %}
            <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% endif %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static', filename='styles/dashboard.css') }}">
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static', filename='styles/sidebars.css') }}">
        <link rel= "stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        {% block head %}
            <title>{% block title %}{% endblock %} - {{ custom['NAVBAR_TITLE'] }}</title>
        {% endblock %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js" integrity="sha512-GMGzUEevhWh8Tc/njS0bDpwgxdCJLQBWG3Z2Ct+JGOpVnEmjvNx6ts4v6A2XJf1HOrtOsfhv3hBKpK9kE5z8AQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{{ url_for('static', filename='js/chartjs-chart-financial.js') }}" type="text/javascript"></script>
        <script src="{{ url_for('static', filename='js/hammer.min.js') }}" type="text/javascript"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@1.0.0/dist/chartjs-adapter-moment.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@1.2.1/dist/chartjs-plugin-annotation.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@1.2.0/dist/chartjs-plugin-zoom.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
        <style>
            a {
                color:black;
                text-decoration:none;
            }
        </style>
    </head>
    <header class="navbar navbar-dark sticky-top {{ custom['NAVBAR_BG'] }} flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-5" href="{{ url_for("main.index_page") }}">{{ custom['NAVBAR_TITLE'] }}</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </header>
    <body class="d-flex flex-column h-100">
        <div class="wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="flex-shrink-0 p-1 bg-white col-md-2">
                        <ul class="list-unstyled ps-0">
                            <li>
                                <a href="{{ url_for("main.index_page") }}" class="btn align-items-center rounded">
                                    Dashboard
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for("main.positions_page") }}" class="btn align-items-center rounded">
                                    All positions
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for("main.history_page") }}" class="btn align-items-center rounded">
                                    Income history
                                </a>
                            </li>
                            <li class="mb-1">
                                <button class="btn btn-toggle align-items-center rounded" data-bs-toggle="collapse" data-bs-target="#activecoins-collapse" aria-expanded="true">
                                    Active coins ({{ coin_list['totals']['active'] }})
                                </button>
                                <div class="collapse show" id="activecoins-collapse">
                                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                        <table class="table table-sm col-1">
                                            {% for item in coin_list['active'] %}
                                                <tr>
                                                    <td><a href="{{ url_for("main.coin_page", coin=item) }}" class="link-dark rounded">{{ item }}</a></td>
                                                    <td class="text-center" data-toggle="tooltip" title="PBR Long">{{ coin_list['active'][item][2] }}</td>
                                                    <td class="table-success text-center" data-toggle="tooltip" title="Buy Orders Long">{{ coin_list['active'][item][0] }}</td>
                                                    <td class="table-danger text-center" data-toggle="tooltip" title="Sell Orders Long">{{ coin_list['active'][item][1] }}</td>
                                                    <td class="text-center" data-toggle="tooltip" title="PBR Short">{{ coin_list['active'][item][5] }}</td>
                                                    <td class="table-success text-center" data-toggle="tooltip" title="Buy Orders Short">{{ coin_list['active'][item][3] }}</td>
                                                    <td class="table-danger text-center" data-toggle="tooltip" title="Sell Orders Short">{{ coin_list['active'][item][4] }}</td>
                                                </tr>
                                            {% endfor %}
                                            <tr class="table-secondary">
                                                <td class="text-center">Total</td>
                                                <td class="text-center">{{ coin_list['totals']['pbr_long'] }}</td>
                                                <td class="text-center">{{ coin_list['totals']['buys_long'] }}</td>
                                                <td class="text-center">{{ coin_list['totals']['sells_long'] }}</td>
                                                <td class="text-center">{{ coin_list['totals']['pbr_short'] }}</td>
                                                <td class="text-center">{{ coin_list['totals']['buys_short'] }}</td>
                                                <td class="text-center">{{ coin_list['totals']['sells_short'] }}</td>
                                            </tr>
                                        </table>
                                    </ul>
                                </div>
                            </li>
                            <li class="mb-1">
                                <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#inactivecoins-collapse" aria-expanded="false">
                                    Inactive coins ({{ coin_list['totals']['inactive'] }})
                                </button>
                                <div class="collapse" id="inactivecoins-collapse">
                                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                        {% for item in coin_list['inactive'] %}
                                            <li><a href="{{ url_for("main.coin_page", coin=item) }}" class="link-dark rounded">{{ item }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>

                    <div class="col-md-10 ms-sm-auto">
                        <div id="content">{% block content %}{% endblock %}</div>
                    </div>
                </div>
            </div>
            {% block footer %}
                <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                    <div class="col-md-4 d-flex align-items-center px-5">
                        <i class="fas fa-rocket"></i>&nbsp;&nbsp;
						<a href="https://github.com/ecoppen/futuresboard" target="_blank" class="text-decoration-none">
							<span class="text-muted">© 2021 Futuresboard</span>
						</a>
                    </div>

                    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
                        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
                        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
                    </ul>
                </footer>
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
		<script>
		$(document).ready(function() {
			$("body").tooltip({ selector: '[data-toggle=tooltip]' });
		});
		</script>
	</body>
</html>

src/futuresboard/templates/error.html
{% extends "base.html" %}
{% block title %}404{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h3><i class="fas fa-exclamation-circle"></i> Error 404</h3>
    </div>
    <p class="important">
        Page not found
    </p>
{% endblock %}

src/futuresboard/templates/history.html
{% extends "base.html" %}
{% block autoreload %}{% endblock %}
{% block title %}Income history{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h3><i class="fas fa-history"></i> Income history</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            {% if filename != "-" %}
                <div class="alert alert-info" role="alert"><i class="fas fa-file-download"></i> Your file has been saved to <code>{{ fname }}</code> which can be downloaded by clicking <a href= "{{ url_for('static', filename=fname) }}">here</a></div><br>
            {% endif %}
            <div class="card">
                <table id="orders" class='table table-sm table-bordered text-center'>
                    <thead class="thead-dark">
                        <tr>
                            <th>Download</th>
                            <th>Time period</th>
                            <th>Total records</th>
                            {% for col in history["columns"] %}
                                <th>{{ col }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for timeframe in history %}
                            {% if timeframe != "columns" %}
                                <tr>
                                    <td><a class="btn btn-outline-primary btn-sm" href="{{ url_for("main.history_page_timeframe", start=history[timeframe]["start"], end=history[timeframe]["end"]) }}" role="button">Save to file</a></td>
                                    <td>{{ timeframe }}</td>
                                    <td>{{ history[timeframe]["total"] }}</td>
                                    {% for col in history["columns"] %}
                                        <td>{{ history[timeframe][col] }}</td>
                                    {% endfor %}
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br><hr><br>
    <div class="row">
        <div class="col-md-7">
            <div class="card">
                <table id="oldfiles" class='table table-sm table-bordered text-center'>
                    <thead class="thead-dark">
                        <tr>
                            <th>Download</th>
                            <th>Filename</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for file in files %}
                            <tr>
                                <td><a class="btn btn-outline-primary btn-sm" href="{{ url_for('static', filename=file) }}" role="button">Download</a></td>
                                <td>{{ file }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>





    <script>
        $(document).ready( function () {
            $('#orders').DataTable({
                "paging": false,
                "searching": false,
                "order": [],
                "info": false,
            });
            $('#oldfiles').DataTable({
                "paging": true,
                "searching": true,
                "order": [[ 1, 'desc' ]],
                "info": true,
            });
        } );
    </script>
{% endblock %}

src/futuresboard/templates/positions.html
{% extends "base.html" %}
{% block autoreload %}<meta http-equiv="refresh" content="60">{% endblock %}
{% block title %}Positions{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h3><i class="fas fa-hand-holding-usd"></i> Positions</h3>
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table id="orders" class='table table-sm table-bordered text-center'>
                <thead class="thead-dark">
                    <tr>
                        <th>Symbol</th>
                        <th>Leverage</th>
                        <th>Pos. Volume</th>
                        <th>Pos. Price</th>
                        <th>Pos. Value</th>
                        <th>Unrealised PnL</th>
                        <th>Current Price</th>
                        <th class="table-success">Buys left</th>
                        <th class="table-success">Next buy</th>
                        <th class="table-success">Distance</th>
                        <th class="table-success">Distance %</th>
                        <th class="table-danger">Sells left</th>
                        <th class="table-danger">Next sell</th>
                        <th class="table-danger">Distance</th>
                        <th class="table-danger">Distance %</th>
                    </tr>
                </thead>
                <tbody>
                    {% for coin in positions %}
                        <tr>
                            <td>{{ coin }}</td>
                            <td>{{ positions[coin][0][0][5]}} {{ positions[coin][0][0][3] }}x</td>
                            <td>{{ positions[coin][0][0][6] }}</td>
                            <td>{{ positions[coin][0][0][4] }}</td>
                            <td>{{ (positions[coin][0][0][6] * positions[coin][0][0][4])|round(2) }}</td>
                            <td>{{ "$%.2f"|format(positions[coin][0][0][2]) }}</td>
                            <td>{{ markprices[coin]|round(8)}}</td>
                            <td>{{ positions[coin][2][0]}}</td>
                            <td>{{ positions[coin][2][4]}}</td>
                            <td>{{ positions[coin][2][5]}}</td>
                            <td>{% if positions[coin][2][4] != "-" %}{{ ((positions[coin][2][5]|float/markprices[coin])*100)|round(2)}}% {% endif %}</td>
                            <td>{{ positions[coin][2][1]}}</td>
                            <td>{{ positions[coin][2][6]}}</td>
                            <td>{{ positions[coin][2][7]}}</td>
                            <td>{% if positions[coin][2][6] != "-" %}{{ ((positions[coin][2][7]|float/markprices[coin])*100)|round(2)}}% {% endif %}</td>
                        </tr>
                    {% if positions[coin][0]|length > 1 %}
                        <tr>
                            <td>{{ coin }}</td>
                            <td>{{ positions[coin][0][1][5]}} {{ positions[coin][0][1][3] }}x</td>
                            <td>{{ positions[coin][0][1][6] }}</td>
                            <td>{{ positions[coin][0][1][4] }}</td>
                            <td>{{ (positions[coin][0][1][6] * positions[coin][0][1][4])|round(2) }}</td>
                            <td>{{ "$%.2f"|format(positions[coin][0][1][2]) }}</td>
                            <td>{{ markprices[coin]|round(8)}}</td>
                            <td>{{ positions[coin][2][2]}}</td>
                            <td>{{ positions[coin][2][8]}}</td>
                            <td>{{ positions[coin][2][9]}}</td>
                            <td>{% if positions[coin][2][8] != "-" %}{{ ((positions[coin][2][9]|float/markprices[coin])*100)|round(2)}}% {% endif %}</td>
                            <td>{{ positions[coin][2][3]}}</td>
                            <td>{{ positions[coin][2][10]}}</td>
                            <td>{{ positions[coin][2][11]}}</td>
                            <td>{% if positions[coin][2][10] != "-" %}{{ ((positions[coin][2][11]|float/markprices[coin])*100)|round(2)}}% {% endif %}</td>
                        </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script>

        $(document).ready( function () {
            $('#orders').DataTable({
                "paging": false,
                "order": [[0,"asc"]],
            });
        } );

    </script>
{% endblock %}